#!/data/data/com.termux/files/usr/bin/bash -e 
trap 'echo "Not permitted"' 2
echo "Enter admin password: "
read -s a
echo $a > temfilpas
if nsu -c cmp -s /data/pass temfilpas
then
echo "Password correct"
else
exit
fi

rm -f temfilpas

currentpass-$(nsu -c cat /data/pass)
echo "Current password: $currentpass"
echo "Write new password"
read -s firstatt
echo "Rewrite new password"
read -s secondatt

if [ "$firstatt" = "$secondatt" ]
then
nsu -c "echo "$firstatt" > /data/pass"
echo "Password changed"
exit 1
else
echo "Try again"
fi
