#!/system/bin/sh

#main reboot termux script
#creates checksum and encrypt data, then reboots device

echo Prepairing device rebooting
echo \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
echo Don\'t use device until reboot
echo \*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*
echo Process will take nearly 1 minute

nsu -c sh /system/10testafter
nsu -c sh /system/encryptandcompress

echo rebooting...

sleep 5

nsu -c reboot
