#!/system/bin/sh

#remount storage files and mount them from multiboot folder

mount -o rw,remount /system
umount -l /data/media
if [ ! -e /data/storage ]; then mkdir /data/storage; fi
mount --bind /data/storage /data/media/0
mount --bind /data/media/0 /storage/emulated/0
umount -l /system
